name: Site build

# workflow triggers
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook
# build process
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
    - run: |
       echo "Triggered"